name: "npm-cache"
description: "Cache npm modules and run npm ci if cache is not hit"

runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Synchronize package.json and package-lock.json
      if: steps.cache-nodemodules.outputs.cache-hit == 'true'
      run: |
        npm install
      shell: bash

    - name: Install Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit == 'true'
      run: |
        npm ci
      shell: bash

    - name: Copy local files only
      if: steps.cache-nodemodules.outputs.cache-hit == 'true'
      run: |
        npm run postinstall
      shell: bash
