name: Code Quality Checks

on:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: "Run Eslint"
    steps:
      - uses: actions/checkout@v3
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - name: Run eslint
        run: |
          npm run lint

  pmd-code-analysis:
    runs-on: ubuntu-latest
    name: "Run PMD"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - name: "Run PMD Checks and fail Build"
        #  PMD CLI does not allow for several paths to be scanned
        # because a dx project could use several packageDirectories
        # (each containing Apex classes), a file list is created
        # and pmd root directory is set to project directory
        run: |
          find ${{ steps.projectname.outputs.result }} -name '*.cls' > apexClassesToScan.txt
          npx pmd -d ${{ steps.projectname.outputs.result }} \
             -R ./node_modules/devops-center-local-config-files/pmd-rulesets/apex-ruleset.xml \
             --file-list apexClassesToScan.txt \
             -f text
        # TODO store results in a file and upload as artifact?

  # commitlint:
  #   runs-on: ubuntu-latest
  #   name: "Run Commitlint"
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: wagoid/commitlint-github-action@v5

  prettier-formatting:
    name: "Format with Prettier"
    needs: [eslint, pmd-code-analysis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: Szandor72/devops-center-actions/.github/install-tooling@main
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml} --no-error-on-unmatched-pattern
          same_commit: True
          # only_changed: True
          prettier_plugins: "prettier-plugin-apex @prettier/plugin-xml"
